### ISSUE TITLE
Doesn't seem to prioritize common words

### ISSUE THREAD

**Issue by lifepillar** [Konfekt/complete-common-words.vim#1]
I'm trying your plugin with a setup like the following:

```vim
set complete=k
set dictionary=spell
set spelllang=en
set spell
let g:common_words_dicts_dir='/path/to/plugin/complete-common-words/dicts'
```

Then I insert `zap` followed by CTRL-N or CTRL-P. The pop-up menu shows `zap` as the first entry, followed by `zapata`, `zapata's`, etc… The word `zapping`, which is the only word starting with `zap` in the plugin's English dictionary, is the penultimate entry of the menu. If I understand correctly, your plugin should show `zapping` as the topmost entry.

Am I doing something wrong?

**Comment by Konfekt** [comment]
Perhaps. When you say you try this plug-in, do you load `plugin/complete-common-words.vim` that should prepend the corresponding dictionary, in this case `en_common.dict` to `&dictionary`? Please check by `set dictionary?`

**Comment by Konfekt** [comment]
Perhaps there is a misinterpretation of

> Copy the contents of this repository into the folder that contains your vim configuration files; it is ~/.vim on Linux and MacOS and %USERPROFILE%/vimfiles on Microsoft Windows.

where the contents are perceived as the dictionaries, whereas both folders, that of the dictionaries `dicts\` as well as `plugin\` are meant.

**Comment by lifepillar** [comment]
Ok, I have found that it sets `dictionary` if I set `spelllang=en` after the buffer has opened. I had `spelllang` set in my `vimrc`, but that doesn't not seem to trigger the update of `dictionary`. Thanks!

**Comment by Konfekt** [comment]
That's strange, as https://github.com/Konfekt/complete-common-words.vim/blob/3098c8e7d306fd83f6291e2684e2bd085df025d6/plugin/complete-common-words.vim#L74 should trigger it on entering any buffer that is spell checked. Perhaps an autocmd for triggering it when `&spell` changes is called for.

**Comment by Konfekt** [comment]
Please check the latest commit with its updated autocmds.

**Comment by lifepillar** [comment]
Thanks, now the settings in my `vimrc` work fine!
